layout_spectrum: 0.2166948
color:
  saturation: 0.267285
  brandStrength: 0.4085491
  lightness: 0.2728347
  rhythmicContrast: 0.5261383
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.5328836
name: Johnhudak
